### ISSUE TITLE
Bug: need to fix command line for delete a repository

### ISSUE THREAD

**Issue by techmannih** [ydv-ankit/repoguard#2]
need to change command line from "**repoguard delete -r repo-name**"  to  "**repoguard delete -r  repo-name  -u 
 username  "** 
, assign me this 
![Screenshot 2024-07-25 112216](https://github.com/user-attachments/assets/dd79447e-8106-4530-8909-a6dfd2a3e2c2)

**Comment by ydv-ankit** [comment]
is it not working ?

**Comment by techmannih** [comment]
not

**Comment by ydv-ankit** [comment]
need to make changes in readme file, code is working.
