### ISSUE TITLE
Feature: make repo private and public with command line

### ISSUE THREAD

**Issue by techmannih** [ydv-ankit/repoguard#3]
Command line for making public repo: "**repoguard  public -r  repo-name  -u  username**"
Command line for making private repo: "**repoguard  private -r  repo-name  -u  username**"

here is example:
![Screenshot 2024-07-25 120743](https://github.com/user-attachments/assets/869a25ee-9faa-4662-b0cb-557d928b6435)

**Comment by ydv-ankit** [comment]
this action can be performed using `repoguard update` command

**Comment by techmannih** [comment]
okay
